Disable SBOM compliance check
Comment out compliance check in workflow.

diff --git a/.github/workflows/sqbms_cxone.yml b/.github/workflows/sqbms_cxone.yml
--- a/.github/workflows/sqbms_cxone.yml
+++ b/.github/workflows/sqbms_cxone.yml
@@ -49,11 +49,11 @@ jobs:
       run: |
         sbomqs compliance --bsi-v2 cx_result_sbom.json --json > compliance.json
         
-        if [ $(jq '.summary.compliant' compliance.json) != "true" ]; then
-          echo "::error::SBOM is not BSI compliant"
-          jq '.recommendations[]' compliance.json
-          exit 1
-        fi
+        #if [ $(jq '.summary.compliant' compliance.json) != "true" ]; then
+        #  echo "::error::SBOM is not BSI compliant"
+        #  jq '.recommendations[]' compliance.json
+        #  exit 1
+        #fi
         
     - name: Upload Reports
       uses: actions/upload-artifact@v4
